# Written by June Skeeter
# March 2024
# Modified by <author>
# Date: <date>

Metadata:
  siteID: SITEID1
  estYear: <YYYY> 
  lat: <latitude>               % North is positive
  long: <longitude>             % West is negative
  TimeZoneHour: <timezone>      % UTC/GMT minus local timezone (e.g., for Pacific standard time, TimeZoneHour = 0 - 8 = -8) 

# Optional parameters to modify default third stage parameters can be added here
Processing:
  ThirdStage:
    Storage: 
      Apply_Correction: True
    REddyProc:
      Run: True
    RF_GapFilling:
      Run: True
  FirstStage:
    DependencyTags:
      tag_EC_Vars:
        tag_LowFreq: >
            T_SONIC
      tag_VWC_Vars: >
        VWC_1_1_1
        VWC_2_1_1
